### ISSUE TITLE
3-5 seconds delay on first switch

### ISSUE THREAD

**Issue by archef2000** [mnordseth/enet-homeassistant#18]
First i am thankful for your work and a otherwise seamless integration.

When i haven't toggled something in the last 1-2 minutes it takes up to 5 seconds until the light is turned on after the command in HA.
I tried to investigate the code but it is very hard to trace the long taking command.

Do you have an idea what the problem could be.

**Comment by mnordseth** [comment]
No idea comes to mind, I have never seen this issue myself. Is this always the case in your installation, or are there specific way to reproduce it?

**Comment by archef2000** [comment]
it is always even after a fresh restart of HA i am running the latest version of both your component and HA but know no way on how to debug this.

**Comment by archef2000** [comment]
Also the integration takes 50s to start:
![grafik](https://github.com/mnordseth/enet-homeassistant/assets/69057532/2640d32b-58d2-4074-87b2-778fb83aa80e)

The delay is the same with blinds.

**Comment by mnordseth** [comment]
I know the integration takes a long time to start, and that is due to how
the inner workings of the enet server. You will see a similar load time if
you logon to the enet server and start commissioning. The enet app is also
very slow to load.

Turning on/off or dimming lights from Home Assistant is more or less
instant in my setup, and I have not heard other complaints either. There
can be a few seconds delay if you change something using a light switch or
the enet app, and before that is reflected in home assistant. The events
generated from the server has a delay.

**Comment by archef2000** [comment]
Turning on/off or dimming lights from Home Assistant takes 3-5 seconds until the light turns on/off

**Comment by archef2000** [comment]
What details could i provide to you.

**Comment by mnordseth** [comment]
I do not really have any idea about the reason for this. Do you experience
delays with any other integration I home assistant? Do you notice any
delays when controlling your lights from the enet app?

**Comment by archef2000** [comment]
I don't have a delay with any other integrations or the eNet app (besides first sync)

**Comment by huglester** [comment]
I think it is an eNET server issue.
I was trying different nodejs libs.
And I spotted one thing, that device (kind of) goes to sleep or so, no sure.
But if you, for a longer time, do not touch lights, yes first one takes longer, like 2 seconds to activate.
Afterwards it goes much faster.

It may be some initial slow connection issues or authentication or so I guess

**Comment by archef2000** [comment]
But once in the app there is no delay

**Comment by huglester** [comment]
Because probably when you are inside an app - it is kind of initated/authed

**Comment by archef2000** [comment]
But in HA i don't have any delay with button presses on the remotes comming in the log

**Comment by mnordseth** [comment]
Hi, you can try to toggle a light using the API to try to seperate if the
issue is a delay on the enet server or if it is home assistant. If you send
med the debug information for the integration, I can guide you on how to do
that.

**Comment by archef2000** [comment]
Delayed on and fast off
```
2023-07-10 09:41:45.195 INFO (MainThread) [custom_components.enet.light] async_turn_on: (Light) {}
2023-07-10 09:41:45.195 INFO (MainThread) [custom_components.enet.aioenet] Light turn_on()
2023-07-10 09:41:45.195 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization callInputDeviceFunction
2023-07-10 09:41:47.512 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization requestEvents
2023-07-10 09:41:48.614 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization requestEvents
2023-07-10 09:41:49.286 INFO (MainThread) [custom_components.enet.light] async_turn_off: (Light) {}
2023-07-10 09:41:49.286 INFO (MainThread) [custom_components.enet.aioenet] Light turn_off()
2023-07-10 09:41:49.286 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization callInputDeviceFunction
2023-07-10 09:41:49.919 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization requestEvents
```
Fast on and off right after the first one
```
2023-07-10 09:41:50.673 INFO (MainThread) [custom_components.enet.light] async_turn_on: (Light) {}
2023-07-10 09:41:50.673 INFO (MainThread) [custom_components.enet.aioenet] Light turn_on()
2023-07-10 09:41:50.673 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization callInputDeviceFunction
2023-07-10 09:41:51.386 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization requestEvents
2023-07-10 09:41:52.153 INFO (MainThread) [custom_components.enet.light] async_turn_off: (Light) {}
2023-07-10 09:41:52.154 INFO (MainThread) [custom_components.enet.aioenet] Light turn_off()
2023-07-10 09:41:52.154 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization callInputDeviceFunction
2023-07-10 09:41:52.634 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization requestEvents
2023-07-10 09:41:54.991 DEBUG (MainThread) [custom_components.enet] Updating value of ActuatorChannel (Name: DeckenlichtKind Type: CT_1F02 Value: 0) to 0
2023-07-10 09:41:54.994 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting https://192.168.188.12/jsonrpc/visualization requestEvents

```

**Comment by mnordseth** [comment]
There seems to be no delay on the home assistant side in any of the cases.
The requests to callInputDeviceFunctionis the call towards the enet server.

If you download the diagnostic for the integration and send to me, I will
help you test it from the command line to further isolate the behaviour.

How long do you have to wait to experience the delay?

**Comment by archef2000** [comment]
Send via E-Mail

**Comment by archef2000** [comment]
Do you have found any idea what the problem could be

**Comment by mnordseth** [comment]
Unfortunately I have no idea what can cause your problem.

**Comment by archef2000** [comment]
It still persists with the latest update. I deleted the integration and added it again.

**Comment by archef2000** [comment]
How can I check what causes the second `/jsonrpc/visualization requestEvents` request?

**Comment by mnordseth** [comment]
I closed this issue as I have no idea what is causing it, and have not
heard from anyone else with similar issues.

/jsonrpc/visualization requestEvents is called in an infinite loop. Not
sure that I understand your question?


-Magnus

**Comment by archef2000** [comment]
In the log it is only requested twice when I switch it the first time after that it is only called once. Is there a way to run it outside of HA to inspect it deeper? Can aioenet.py be run standalone?

**Comment by mnordseth** [comment]
Yes, clone the repo, and then

`python  examples/run_cli.py server_uri username password`

**Comment by Fred-the-man** [comment]
I have exactly the same Problem. The first action has a delay of 4-5 seconds, the next are much faster. It feels like that the connection to the eNet Server is closed After a short while and the reconnecting needs time To be established.

**Comment by archef2000** [comment]
@mnordseth I am currently trying to test the problem with the cli, but is there an easier way to get a device by Name so that the channel can be set? Without checking each device when it gets printed?

**Comment by archef2000** [comment]
To test the delay I have this snippet for the example cli for line [examples/run_cli.py#L28](https://github.com/mnordseth/enet-homeassistant/blob/main/examples/run_cli.py#L28):
```python3
        log = logging.getLogger(__name__)
        for device in enet.devices:
            if device.channels[0].name == "<***>":
                print(device)
                print(device.channels[0].get_current_value("onOff"))
                await asyncio.sleep(1)
                log.info("now")
                await device.channels[0].set_value("brightness", 0)
                log.info("done")
                print(device.channels[0].get_current_value("onOff"))
```

with the 1s sleep it takes 3 seconds to run "set_value" without it there is no delay.

log with one 1s:
```
False
2024-12-25 16:08:56,069 DEBUG enet.aioenet -- Requesting https://192.168.188.12:443/jsonrpc/visualization requestEvents
2024-12-25 16:08:57,071 INFO  __main__ -- now
2024-12-25 16:08:57,071 DEBUG enet.aioenet -- Requesting https://192.168.188.12:443/jsonrpc/visualization callInputDeviceFunction
2024-12-25 16:09:00,341 INFO  __main__ -- Setted value to 0
False
```
log without sleep:
```
False
2024-12-25 16:07:28,416 INFO  __main__ -- now
2024-12-25 16:07:28,416 DEBUG enet.aioenet -- Requesting https://192.168.188.12:443/jsonrpc/visualization callInputDeviceFunction
2024-12-25 16:07:28,417 DEBUG enet.aioenet -- Requesting https://192.168.188.12:443/jsonrpc/visualization requestEvents
2024-12-25 16:07:28,655 INFO  __main__ -- Setted value to 0
False
```

When commenting out the "requestEvents" request in the initialize function there is no delay:
https://github.com/mnordseth/enet-homeassistant/blob/main/custom_components/enet/aioenet.py#L81

When adding this after the first snippet there is a delay of more than 10 seconds with event request in the background and 3-6 seconds without (the line in the initialize function):
```python
                await asyncio.sleep(16) # 16 or higher
                log.info("now2")
                await device.channels[0].set_value("brightness", 50)
                log.info("done2")
```

**Comment by mnordseth** [comment]
Just to ensure I understand this correctly. If you comment out the requestEvents loop, you see no unexpected delays, but if you leave that loop in there, there are no unexpected delays?

**Comment by archef2000** [comment]
Sorry for my wording. So as long as the event read is not active there is no delay.

**Comment by mnordseth** [comment]
I was unable to reproduce that. Can you share your full test code?

**Comment by ChrisSoelder** [comment]
Hi @mnordseth!

I might have 2 suggestions for further investigating the issue:

First of all there are different hardware revisions of the eNet Server and the first iterations used to have some performance issues, especially with SSL enabled. 
I had issues with our Server in that regard even with the native app (e.g. scenes would take quite a while to activate etc.). We contacted Gira Support back then and they told us that they recommend disabling SSL due to known performance issues with the earlier models. In the end we got our Server replaced by Gira with a newer one, which fixed the problem for us.

Hence it might be interesting which hardware revisions are involved.
You can check the hardware version in the system setting of the admin interface.
Hardware version 2 is already the improved one.

<img width="823" alt="Image" src="https://github.com/user-attachments/assets/166db0f4-ebbc-46b4-bb26-5609f9042f8c" />

There exists a ping method for the jrpc interface, maybe polling that one every few seconds could be a workaround for the handshake issue?
```
// URL {{enet_server_url}}/jsonrpc/management
// GET Request Body
{
    "jsonrpc":"2.0",
    "method":"ping",
    "params":null,
    "id":"{{request_counter}}"
}
``` 

I hope this helps ;)

**Comment by huglester** [comment]
Hey,

> In the end we got our Server replaced by Gira with a newer one, which fixed the problem for us.

which model did you get? so would be easier to migrate?

**Comment by archef2000** [comment]
Hardware version: 1
Software version: 2.4.0 (46892)
Sences are near instant in the app

**Comment by archef2000** [comment]
HTTPS:
A wait of 1 or 5 seconds results in a 100 to 200 ms response. 30,20 or 60 seconds results in ~2.3s responses.

Running a ping every 14s like @ChrisSoelder recommended fixes that and every update takes 100ms

In the EnetClient:
```python
    def ping(self):
        return self.request(URL_MANAGEMENT, "ping", None)
```
The testfile:
```python
"""Example script for using aioenet connecting to a Enet Smart Home Server."""
import argparse
import asyncio
import logging
import random
import time
from os.path import abspath, dirname
from sys import path

path.insert(1, dirname(dirname(abspath(__file__)))+"/custom_components/")

from enet import aioenet

parser = argparse.ArgumentParser(description="AIO Enet Smart Home command line example")
parser.add_argument("host", help="URI of Enet Smart Home Server, ie http://enet-server")
parser.add_argument("username", help="Username")
parser.add_argument("password", help="Password")
parser.add_argument("--debug", help="enable debug logging", action="store_true")
args = parser.parse_args()

async def main():
    if args.debug:
        logging.basicConfig(
            level=logging.DEBUG,
            format="%(asctime)-15s %(levelname)-5s %(name)s -- %(message)s",
        )
    else:
        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)-15s %(levelname)-5s %(name)s -- %(message)s",
        )

    async def random_update(channel):
        for i in range(100):
            wait = random.choice([1, 5, 30, 60])
            logging.info("Random update task waiting %d", wait)
            await asyncio.sleep(wait)

            current = c.get_current_value("onOff")
            logging.debug("Updating value of %s from %d", channel.name, current)
            ts = time.time()
            await c.set_value("brightness", current+1)
            te = time.time()
            logging.info("Updated value of %s from %d in %2.2fs", channel.name, current, (te - ts))

    async def ping_loop():
        while True:
            logging.info("Pinging Enet Server")
            te = time.time()
            await enet.ping()
            logging.debug("Ping took %2.2fs", time.time() - te)
            await asyncio.sleep(14)


    async with aioenet.EnetClient(args.host, args.username, args.password) as enet:
        print(f"Connected to {args.host}")
        to_update = None
        for device in enet.devices:
            #print(device)
            #print("\n".join(["  " + str(c) for c in device.channels]))
            for c in device.channels:
                if c.name == "DeckenlichtKind":
                    print(c)
                    to_update = c

        def print_event(*args):
            logging.info("Got event")

        enet.subscribe(print_event)
        asyncio.create_task(ping_loop())
        await asyncio.create_task(random_update(to_update))

        logging.info("\n\nWaiting for events...")

        await asyncio.sleep(10)

try:
    asyncio.run(main())
except KeyboardInterrupt:
    pass
```

HTTP:
I even turned of HTTPS in the admin interface.
error:
```log
2025-01-25 17:15:09,247 DEBUG enet.aioenet -- Requesting http://192.168.188.12/jsonrpc/management userLogin
2025-01-25 17:15:11,456 WARNING enet.aioenet -- Request to https://192.168.188.12/jsonrpc/management failed with status 405
2025-01-25 17:15:11,456 DEBUG enet.aioenet -- Requesting http://192.168.188.12/jsonrpc/management setClientRole
2025-01-25 17:15:11,527 WARNING enet.aioenet -- Request to https://192.168.188.12/jsonrpc/management failed with status 405
2025-01-25 17:15:11,527 DEBUG enet.aioenet -- Requesting http://192.168.188.12/jsonrpc/visualization getLocations
2025-01-25 17:15:11,599 WARNING enet.aioenet -- Request to https://192.168.188.12/jsonrpc/visualization failed with status 405
Traceback (most recent call last):
  File "/config/enet-homeassistant/examples/test.py", line 78, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/config/enet-homeassistant/examples/test.py", line 55, in main
    async with aioenet.EnetClient(args.host, args.username, args.password) as enet:
  File "/config/enet-homeassistant/custom_components/enet/aioenet.py", line 84, in __aenter__
    await self.initialize()
  File "/config/enet-homeassistant/custom_components/enet/aioenet.py", line 79, in initialize
    self.devices = await self.get_devices()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/enet-homeassistant/custom_components/enet/aioenet.py", line 241, in get_devices
    device_locations = await self.get_device_locations()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/enet-homeassistant/custom_components/enet/aioenet.py", line 295, in get_device_locations
    locations = await self.get_locations()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/enet-homeassistant/custom_components/enet/aioenet.py", line 269, in get_locations
    return result["locations"]
           ~~~~~~^^^^^^^^^^^^^
TypeError: 'ClientResponse' object is not subscriptable
2025-01-25 17:15:11,675 ERROR asyncio -- Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7113c6c52f60>
2025-01-25 17:15:11,675 ERROR asyncio -- Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7113c6c60a70>, 4244468.078554421)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7113c6c60dd0>, 4244468.118100748)]']
connector: <aiohttp.connector.TCPConnector object at 0x7113c6c52f30>
```
When trying with curl by replaying the ping request of the admin interface (changing https to http) I just get 302 to the https url.

@ChrisSoelder 
How long did you have the old server until you got it replaced?
Was it for free? Under waranty?

**Comment by ChrisSoelder** [comment]
Hi all!
Just to clarify. I also experience a short delay on first switch, but it's not 3-5 seconds. Just something around 1 or 2 seconds. Which is not really bothering me.

@huglester 
As shown in the screenshot, I now have hardware version 2. I am not sure whether you can order a specific version of the server. I think this is just an internal revision of the product itself.

@archef2000 
Yes we got it replaced for free after we had contacted Gira support but we did this quite soon after installing the System in 2019. As far as I remember, back than we should have gotten the newer version in the first place already. But I can be mistaken.

**Comment by mnordseth** [comment]
I have made a new release of the intragration that will ping the server every 15s if connected via https. I would appreciate if you test and give me feedback on if this resolves the issue or not.

**Comment by archef2000** [comment]
Thanks for the quick change. Will try it out, but 15 seconds were a bit too long sometimes in my tests. Do you mind adjusting that?

**Comment by huglester** [comment]
In the above comments somebody mentioned especialy 14s sleep. Not 15. Maybe it is the key. 

I will try this patch myself later

Thanks

**Comment by archef2000** [comment]
It would mean a 3 second response time in the 1 second where the ping is late every 15 seconds. So if you toggle a light in that 1/15 time window you will have a delay.

**Comment by archef2000** [comment]
I now get around 0.5 seconds response time.

**Comment by Fred-the-man** [comment]
Same to me. I have also Version 1 of the server. The performance is much better now. Thank's a lot!

**Comment by mnordseth** [comment]
Thank you all for feedback on this. I have made a small update increasing the keepalive timeout to 30s and change the ping loop to 28s. Let me know how this works for you.

**Comment by gillmar** [comment]
I’m running version 1 of the Jung server and installed the newest version this morning.

Everything is very fast now, feels like a young dog with too much power now.

Thx a lot to everyone making that real!!

**Comment by huglester** [comment]
Thanks. 

This seems to have fixed the delay.

Hope it is for good!
