### ISSUE TITLE
Error setting up entry Enet Smart Home for enet

### ISSUE THREAD

**Issue by gillmar** [mnordseth/enet-homeassistant#26]
Hello Magnus,
I was looking since years for an integration of my Jung eNet Smart Home into a good smart home solution and to escape the Jung-/tado-only world.
And now I found it and I'm happy to contribute if it is running for me.

Right now I have the issue that your enet-homeassistant v0.997 integration doesn't like my Jung eNet Server (running 2.3.1 (46841)). I'm running my server on https.

Any idea? May I ask you for support?

2024-06-11 19:33:27.566 DEBUG (MainThread) [custom_components.enet] EnetCoordinator.__init__()
2024-06-11 19:33:27.566 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting http://192.168.1.200/jsonrpc/management userLogin
2024-06-11 19:33:29.625 WARNING (MainThread) [custom_components.enet.aioenet] Request to https://192.168.1.200/jsonrpc/management failed with status 405
2024-06-11 19:33:29.625 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting http://192.168.1.200/jsonrpc/management setClientRole
2024-06-11 19:33:29.752 WARNING (MainThread) [custom_components.enet.aioenet] Request to https://192.168.1.200/jsonrpc/management failed with status 405
2024-06-11 19:33:29.753 DEBUG (MainThread) [custom_components.enet.aioenet] Requesting http://192.168.1.200/jsonrpc/visualization getLocations
2024-06-11 19:33:29.815 WARNING (MainThread) [custom_components.enet.aioenet] Request to https://192.168.1.200/jsonrpc/visualization failed with status 405
2024-06-11 19:33:29.815 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Enet Smart Home for enet
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enet/__init__.py", line 38, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id] = hub
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enet/aioenet.py", line 153, in get_devices
    device_locations = await self.get_device_locations()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enet/aioenet.py", line 203, in get_device_locations
    locations = await self.get_locations()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enet/aioenet.py", line 177, in get_locations
    return result["locations"]
           ~~~~~~^^^^^^^^^^^^^
TypeError: 'ClientResponse' object is not subscriptable

**Comment by gillmar** [comment]
I configured http instead of https by mistake. Solved.

**Comment by gillmar** [comment]
I configured http instead of https by mistake. Solved.
